### ISSUE TITLE
How to use xcopy-msbuild with Roslyn?

### ISSUE THREAD

**Issue by LivewareIssue** [jaredpar/xcopy-msbuild#6]
I'm trying to write a code indexer using Roslyn (targeting a similar format to LSIF) but i'm having trouble getting it to work reliably in the different environments in which it will be deployed.

The short of it is that I can't guarantee that there will be a working version of dotnet on the target machines meaning a) I need to publish a single-file app and b) need to ship the indexer with everything required by Roslyn to analyse C# projects (i.e. MSBuild + reference assemblies).
 
The current set-up i'm trying looks like this:

I have references to the RoslynTools.MSBuild and Basic.Reference.Assemblies.Net60 packages

```
<PackageReference Include="Basic.Reference.Assemblies.Net60" Version="1.4.2"/>
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.6.0"/>
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.6.0"/>
<PackageReference Include="Microsoft.Build.Locator" Version="1.5.5"/>
<PackageReference Include="RoslynTools.MSBuild" Version="16.8.0-preview1" ExcludeAssets="all"/>
```

I then have a target to copy the contents of RoslynTools.MSBuild on build/publish

```
<Target Name="CopyMSBuildAssemblies" AfterTargets="Build;Publish">
  <Copy SourceFiles="@(MSBuildAssemblies)" DestinationFiles="@(MSBuildAssemblies-&gt;'$(FinalOutputPath)\MSBuild\%(RecursiveDir)%(Filename)%(Extension)')"/>
</Target>
```

which seems to be working correctly, then, in my app, I try to register the bundled copy with MSBuildLocator and open a project

```
// Point the the copied contents of RoslynTools.MSBuild
var msbuildPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "MSBuild");

Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", Path.Combine(msbuildPath, "MSBuild.exe"), EnvironmentVariableTarget.Process);
MSBuildLocator.RegisterMSBuildPath(msbuildPath);

var workspace = MSBuildWorkspace.Create();
var project = await workspace.OpenProjectAsync(projectPath);
var newProject = project.WithMetadataReferences(Basic.Reference.Assemblies.Net60.References.All);
workspace.TryApplyChanges(newProject.Solution);
```

but I'm getting exceptions on project open (workspace create seems to work), e.g.

```
Unhandled exception. System.TypeLoadException: Could not load type 'System.Diagnostics.Tracing.EventSource' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Build.Execution.BuildManager.BeginBuild(BuildParameters parameters)
   at Microsoft.CodeAnalysis.MSBuild.Build.ProjectBuildManager.StartBatchBuild(IDictionary`2 globalProperties)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadProjectInfoAsync(String projectFilePath, ProjectMap projectMap, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync(String projectFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /some/redacted/path/Indexer/Indexer.csproj__srcs/Program.cs:line 37
   at Program.<Main>(String[] args)
```

I didn't think setting the `MSBUILD_EXE_PATH` environment variable was necessary, but I get other issues without it (i.e. `Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')`)

I'm mostly asking this question to sanity-check this approach, if not debug this specific issue... should this work / is what I want to do possible? Apologies in advance for the noob question..i'm very much stabbing in the dark here and haven't found a similar use case searching GitHub to verify against.

**Comment by LivewareIssue** [comment]
The output of `dotnet --info` on the machine i'm building on, if that helps

```
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /some/redacted/path/third-party/dotnet/linux-x64/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [/some/redacted/path/third-party/dotnet/linux-x64/sdk]
  6.0.100 [/some/redacted/path/third-party/dotnet/linux-x64/sdk]
  6.0.405 [/some/redacted/path/third-party/dotnet/linux-x64/sdk]
  6.0.408 [/some/redacted/path/third-party/dotnet/linux-x64/sdk]
  7.0.302 [/some/redacted/path/third-party/dotnet/linux-x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/some/redacted/path/third-party/dotnet/linux-x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/some/redacted/path/third-party/dotnet/linux-x64]

global.json file:
  Not found
```
